theme: jekyll-theme-minimal
#remote_theme: "godalming123/minimal"
#plugins:
#- jekyll-remote-theme
#color-scheme: dark
title: Greg Lankenau's Data Science Portfolio
description: Not Your Ordinary Data Scientist
